### ISSUE TITLE
Cannot create more than four graphs

### ISSUE THREAD

**Issue by joshcho** [kraison/vivace-graph-v3#34]
Not sure if having multiple graphs is the intended use case, but on my machine with SBCL, after calling make-graph on four graphs, calling make-graph halts the interpreter.

**Comment by kraison** [comment]
Multiple graphs is definitely not an intended use case. The memory requirements would quickly become an issue. You can think of a graph as a disk-based extension to the Lisp working memory space, with its own garbage collector. It would take a fair amount of redesign to use multiple graphs. And linking nodes in one graph to nodes in another will definitely have undefined rests.
